name: Setup Ingrid Context
description: |
  This action checkouts Ingrid actions private repository and also the application repository.
  In addition to the checkout, it also uses FranzDiebold/github-env-vars-action to pass more env variables.

inputs:
  path:
    description: The path where the actions should be checked out
    default: "ingrid-actions"
    required: false
  ref:
    description: The revision of the ingrid-actions you are trying to checkout
    default: ""
    required: false
  working_directory:
    description: The working directory where the application should be checked out
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - uses: FranzDiebold/github-env-vars-action@v2

    - name: Setup GOPRIVATE Variable
      shell: bash
      run: echo "GOPRIVATE=github.com/shipwallet" >> $GITHUB_ENV

    - name: Checkout Ingrid Actions Repo
      uses: actions/checkout@v4
      with:
        repository: shipwallet/github-actions
        token: ${{ env.GH_TOKEN_SW_BOT }}
        path: ${{ inputs.path }}
        ref: ${{ inputs.ref }}

    - name: Checkout Application Repo
      uses: actions/checkout@v4
      with:
        path: ${{ env.CI_REPOSITORY_NAME }}
        token: ${{ env.GH_TOKEN_SW_BOT }}

    - name: Set CI_REPOSITORY_NAME
      run: echo "CI_REPOSITORY_NAME=${{ inputs.working_directory || env.CI_REPOSITORY_NAME }}" >> $GITHUB_ENV
